### ISSUE TITLE
use OAuth2 for login management with external auth sources

### ISSUE THREAD

**Issue by ableeb** [plone/plone.login#21]
Facebook & Google are the base case.

@zombified is working on a PAS plugin that leverages  [authomatic](http://peterhudec.github.io/authomatic/index.html) or maybe a different library

**Comment by ableeb** [comment]
Python social auth shows some promise as it already plugs into/supports other Python web frameworks http://psa.matiasaguirre.net/docs/index.html

**Comment by saily** [comment]
I'm planing to implement by:
- Write OAuth PASPlugin (some similar stuff is already out there)
- Provide a basic configureable OAuth Login Handler. This could be configured using GS and the plone registry but also provide some common provider for Google, Facebook, Twitter, etc.

How should we make these configureable?
- plone.registry through GS?
- plone.registry through controlpanel forms?
- ZMI (-1)

The second thing i'm not sure: shall we really ship this with `plone.login` or create another generic package `plone.oauth` which is a dependency of `plone.login`?

From my point of view this is a low hanging fruit, most stuff is already available, i would just ensure it's working, write some tests and align it to our coding standards. Users would love it!

**Comment by ableeb** [comment]
@saily Sounds great! As for making the login handler configurable I think p.registry via a controlpanel would be preferred. We should be able to export the registry and get any user configured settings that way. 

Also, I think having it as part of the plone.login package would be fine - one of the ideas behind plone.login was to modernize the login story. Having a way to login/register via Google/Facebook/Twitter out of the box fits in nicely as part of the login modernization story.

**Comment by djay** [comment]
We are about to work on a login handler that allows redirecting on unauthorised and is configurable in different places in the site. This way we can allow certain files and folders to have a different login scheme. This won't be plone.login however as it will need to work on older versions.

**Comment by miohtama** [comment]
@saily you might be interested in the following Python projects

peterhudec.github.io/authomatic/

http://pythonhosted.org//velruse/

**Comment by saily** [comment]
Discussion with @jensens

- We should use [Authomatic](http://peterhudec.github.io/authomatic) as OAuth Wrapper
- Create a `pas.plugins.authomatic`
- Allow plugins to register for LoginForm
- Retrieve/sync data on `IUserLoggedInEvent`
- BTree for all users
- PersistentDict for NonMutablePropertySheet
- ... finally we decided we should write a PLIP for the whole login procedure.
