### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by vangheem** [plone/plone.login#38]
What is the status of plone.login? Is there a desire to still attempt to put this into 5.0 or are we thinking a 5.1 at this point?

I'm wondering if we need to recommend sprinting to be done on this or if I should attempt to help.

**Comment by ableeb** [comment]
Probably 5.1 at this point. Sprinting would also probably be a good idea - my projects haven't required this so I've pretty much ignored it. Help is always welcome :+1:

**Comment by vangheem** [comment]
I'll probably hold off if we're thinking 5.1. I also have an itch to revamp a lot of the acl_user related stuff for 5.1. This package is related.
