### ISSUE TITLE
integrate with collective/pas.plugins.authomatic

### ISSUE THREAD

**Issue by ableeb** [plone/plone.login#39]

**Comment by pbauer** [comment]
@saily can you comment on the state of your branch https://github.com/plone/plone.login/tree/saily-oauth? How does it relate to https://github.com/collective/pas.plugins.authomatic?

**Comment by saily** [comment]
@pbauer sorry, i can't remember, but a long time ago i tried to adapt some ideas from authomatic and was talking about it to @jensens. It seems pas.plugins.authomatic ships the functionality i wanted to build.

The current state therefore is *unmaintained for a long time* ;-)

**Comment by pbauer** [comment]
thanks for the info!

**Comment by jensens** [comment]
see #44
