### ISSUE TITLE
setting password after self-registration fails

### ISSUE THREAD

**Issue by vincero** [plone/plone.login#45]
Tested with Plone-5.1rc2:

Trying to set a password after registration fails and produces following traceback:

2018-01-13 16:17:29 ERROR Zope.SiteErrorLog 1515856649.750.767825892314 http://localhost:9080/Plone/@@register
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 239, in __call__
  Module plone.app.users.browser.register, line 82, in render
  Module OFS.Traversable, line 300, in unrestrictedTraverse
   - __traceback_info__: ([], 'registered')
KeyError: 'registered'
[6] > /home/zope/Plone/.cache/eggs/Zope2-2.13.26-py2.7.egg/OFS/Traversable.py(300)unrestrictedTraverse()
-> raise e

**Comment by jensens** [comment]
fixed with https://github.com/plone/plone.app.users/pull/71
